### ISSUE TITLE
Hard coded soil check

### ISSUE THREAD

**Issue by MT-Modder** [tenplus1/farming#12]
Could you please check for soil group level 3 [here](https://github.com/tenplus1/farming/blob/master/init.lua#L425) instead of strictly "farming:soil_wet". That would allow plants to grow on custom wet soils added by mods like [mine](https://github.com/MT-Modder/hydroponics).

**Comment by tenplus1** [comment]
Updated, thanks for the suggestion.

**Comment by MT-Modder** [comment]
Awesome thanks!
