### ISSUE TITLE
Check air above plant for light instead of the plant itself.

### ISSUE THREAD

**Issue by MT-Modder** [tenplus1/farming#14]
One more request to get my mod fully operational with yours.

Could you please change [light_pos ](https://github.com/tenplus1/farming/blob/master/init.lua#L431)to:
```{x = pos.x, y = pos.y + 1, z = pos.z}```

That way modders can just check for air rather than a lot of different, non-builtin, nodes.

With this last change I can grow your plants underground or at night using my grow lights:
![capture](https://cloud.githubusercontent.com/assets/7414772/15582039/07dccb6c-233d-11e6-813e-2a953f0f0e9d.PNG)

**Comment by tenplus1** [comment]
Done, a better idea to check light above plant than inside it :)

**Comment by MT-Modder** [comment]
Sweet! Thank you.
