### ISSUE TITLE
Change MIN_LIGHT or allow it through an optional config file

### ISSUE THREAD

**Issue by AcidNinjaFWHR** [tenplus1/farming#19]
Hi.

On our server Mynetest, we noticed that farming was not possible underground, even though we had put lamps on the ceiling.
We consider this might be possible and had to change the MIN_LIGHT to 8 instead of 13.

What do you think ?

Thanks in advance.

**Comment by tenplus1** [comment]
Acid - farming can be done underground, remember that light level of 13 and over are needed to crop crops and it must be beside the crop to work (e.g. meselamp next to crop or straight above)
