### ISSUE TITLE
Outdated from the orinigal farming

### ISSUE THREAD

**Issue by BrunoMine** [tenplus1/farming#27]
Here is some outdated things.

- new soils
- wheat aspect (like in minecraft and not like the grass)

Why this mod can not work harmonically with the original farming? Currently farming is a great API. This would make this mod compatible with other farming mods.

**Comment by tenplus1** [comment]
I removed the sand soil on purpose because I didn't like it, don't worry though as any sand soil in use will alias to normal soil.  Notice that this mod replaces the default farming mod and uses it's own compatible api with new features.

**Comment by BrunoMine** [comment]
Okay, buy can you update the wheat plant?
![wheat](https://user-images.githubusercontent.com/7986261/29278392-f8ac90e8-80ea-11e7-94ce-14026ecd9dc6.png)

**Comment by tenplus1** [comment]
changed
