### ISSUE TITLE
Rarity setting for to spawn plants

### ISSUE THREAD

**Issue by BrunoMine** [tenplus1/farming#28]
I wish I could reduce the frequency of plant spawn. After a short walk I was full of food in the inventory and don't needing to plant them.
I'm just requesting a new rarity setting (`minetest.conf`).That way i will not need to change the source code each update.
I like to make the game more difficult.

**Comment by tenplus1** [comment]
added

**Comment by BrunoMine** [comment]
That was the result I got with the tests.
`farming.rarety = 0.00000001`
![rariry error](https://user-images.githubusercontent.com/7986261/29366991-dccc99e4-8271-11e7-8b1d-f802fde382fc.png)
The [Scale](https://github.com/tenplus1/farming/blob/master/mapgen.lua#L15) does not define the rarity of crops, but homogeneity.

**Comment by tenplus1** [comment]
I assumed is spread out the crops more and making them rarer to find, maybe I need to look into this and find another method.
