### ISSUE TITLE
crash when set time_speed=0

### ISSUE THREAD

**Issue by crabman77** [tenplus1/farming#3]
I set "time_speed=0" in minetest.conf on my local debug server, now farming crash.
>> ERROR[main]: Lua: Runtime error from mod 'farming' in callback node_on_timer(): ...e/bin/../mods/farming/init.lua:98: attempt to perform arithmetic on upvalue 'SECS_PER_CYCLE' (a nil value)

line 74 ,https://github.com/tenplus1/farming/blob/master/init.lua#L74
>> local SECS_PER_CYCLE = (time_speed > 0 and 24 * 60 * 60 / time_speed) or nil

.

Otherwise, maybe this code interest, it's a autorefill plant/seed https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/8a82fb2bb57083e4d72ec3dd02d4294fe932490b

**Comment by tenplus1** [comment]
Strange issue, but just incase I've changed the SECS_PER_CYCLE to default to 0 instead of nil...  As for the auto-refill, that's a handy feature and will be glad to add it (for cocoa beans also)...  Thank you...
