### ISSUE TITLE
beans/beanpole grapes/trellis can placed in protected areas

### ISSUE THREAD

**Issue by crabman77** [tenplus1/farming#4]
There is no test for protected areas when placing beans/beanpole grapes/trellis
https://github.com/tenplus1/farming/blob/master/beanpole.lua#L11
https://github.com/tenplus1/farming/blob/master/beanpole.lua#L65

https://github.com/tenplus1/farming/blob/master/grapes.lua#L7
https://github.com/tenplus1/farming/blob/master/grapes.lua#L61

**Comment by tenplus1** [comment]
Fixed, thanks for letting me know.
