### ISSUE TITLE
Missing straw stairs/slabs

### ISSUE THREAD

**Issue by Ezhh** [tenplus1/farming#40]
Hi Ten, some time ago MTG moved the registration for straw stairs and slabs to the farming mod, since it was incorrect for stairs to depend on farming. 

Could you please add straw slabs and stairs registration here as well so that those who use MTG stairs mod with this mod won't lose these two nodes?

**Comment by tenplus1** [comment]
0.4.16 stable has straw stairs inside 'stairs' mod itself so would cause dependency issues having both mods depend on one another, I may be able to add an alias to fix the issue though.

**Comment by Ezhh** [comment]
Alias or fix in separate branch is fine (maybe even a note in readme would do so people realise that they need to manually add this for now if using dev version?)
