### ISSUE TITLE
strange missing rare images

### ISSUE THREAD

**Issue by mckaygerhard** [tenplus1/farming#44]
revising i has a missing images:  soil.png soil_wet.png soil_wet_side.png

seems its not enought have the farming:soild, etc etc .. maybe due the soil.lua declarations..

i duplicate the farimg_soil.png to soil.png and now works, coudl you check that?

**Comment by tenplus1** [comment]
How old is your minetest version ? those missing textures were renamed to farming_soil.png and farming_soil_wet.png quite some time ago...

**Comment by mckaygerhard** [comment]
lasted minetes pufff "update update" you sound like Mocosoft agent!
