### ISSUE TITLE
Problem with register_plant()

### ISSUE THREAD

**Issue by acmgit** [tenplus1/farming#48]
Hello,
seems, the problem with the default-farming compatibility is only partielly solved.

![screenshot_20180525_214137](https://user-images.githubusercontent.com/9446707/40563748-3c89dcc0-6066-11e8-8496-87f6b652d6a7.png)

This is my version of cucina_vegana under the branch farmtest. This version works well with the farming-mod from default, the plants grows.
With your farming-mod in this version, there is a strange behavior: Not all plants are growing and they grows in a "pattern". Take a look on the Screenshot.

The other Version with the different files for farming_default and farming_redo works well and have no problems.

Maybe i do something wrong in this version, perhaps you have an idea ;-).

Greetings,
Clyde (from the Forum).

**Comment by tenplus1** [comment]
Remove the {growing=1} group from all your crops registered with farming.register_plant() as that group is added automatically for plants that need it.
