### ISSUE TITLE
Minetest crash when time_speed == 0

### ISSUE THREAD

**Issue by Rogier-5** [tenplus1/farming#5]
When time_speed is 0, minetest crashes when trying to grow crops:

[code]
22:30:24: ERROR[main]: ServerError: caught (...)
22:30:24: ERROR[main]: stack traceback:
22:30:24: ERROR[main]:  [C]: in function 'swap_node'
22:30:24: ERROR[main]:  /home/rogier/.minetest/mods/farming/init.lua:377: in function \</home/rogier/.minetest/mods/farming/init.lua:334>
[/code]

**Comment by tenplus1** [comment]
Fixed.
