### ISSUE TITLE
Rhubarb is not generated

### ISSUE THREAD

**Issue by Rogier-5** [tenplus1/farming#7]
After extensive searching of a freshly-generated map, I haven't been able to find any rhubarb. I did find numerous blueberry and raspberry plants, many of them not far from trees (i.e. in areas where rhubarb could / should have been generated as well).

After changing 'offset' from 0 to 1 in the noise_params, large amounts of other plants were generated, but still no rhubarbs. Actually, whereas all other grass was almost fully covered with plants, the areas under each tree, where rhubarb might have been, were consistently empty.

**Comment by tenplus1** [comment]
Rhubarb generated from level 3 to 14 next to tree's in the shade, although the mapgen's have been changed since then and it may not generate of late so I will remove the tree part and just have it appear at those levels.

**Comment by Rogier-5** [comment]
I retested it on a more recent version of minetest (that is: the current git version), and using that version, rhubarb is generated. Also, the areas under trees are no longer empty when the noise offset is set to 1.

So your code is OK, and apparently, it was a bug in minetest which has been fixed since, maybe even some time ago: the older minetest version I used was 0.4.12...
